env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  process: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - svelte3
overrides:
  - files: ['**/*.svelte']
    processor: 'svelte3/svelte3'
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
  no-trailing-spaces:
    - error
