env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:svelte/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  process: readonly
  __APP_VERSION__: readonly
  __BUILD_DATE__: readonly
parserOptions:
  ecmaVersion: 2024
  sourceType: module
plugins:
  - svelte
overrides:
  - files: ['**/*.svelte']
    parser: 'svelte-eslint-parser'
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
  no-trailing-spaces:
    - error
